### ISSUE TITLE
Scribe header case-sensitivity

### ISSUE THREAD

**Issue by zacharyatstreak** [scribejava/scribejava#433]
HTTP headers are defined to be case-insensitive. The standard display I've seen is to have the first letter uppercase--can you lowercase the header name before looking for it in the Request object, so it returns the correct result when I use this standard format?  I've run into this twice now.

**Comment by depsypher** [comment]
Looks like the headers being case sensitive breaks stackexchange currently.

StackExchange compresses responses whether you ask for them that way or not:
https://api.stackexchange.com/docs/compression

But the header in the response is "content-encoding" not ""Content-Encoding".

Calling `Response.getBody()` delegates to `parseBodyContents()`, which fails to find the gzip encoding here:
`if ("gzip".equals(getHeader("Content-Encoding"))) {`

So instead of calling getBody() I have to do this directly:
`StreamUtils.getGzipStreamContents(resp.getStream()))`

I would prefer that getBody() could detect gzip on stackexchange appropriately.
Thanks!

**Comment by depsypher** [comment]
It appears that the reason Content-Encoding was coming in lower-cased in my case had to do with Google Appengine's implementation of HttpUrlConnection doing that normalization... In any case, it seems like a scenario that scribe should handle. I'll submit a PR.

**Comment by kullfar** [comment]
Pull Request was merged to the master
