### ISSUE TITLE
You are using ning's http client as a dependency but this no longer exists

### ISSUE THREAD

**Issue by coderbec** [scribejava/scribejava#678]
I'm pretty sure it got migrated to this https://github.com/AsyncHttpClient/async-http-client, which you've also for some reason included in the maven dependencies.

**Comment by kullfar** [comment]
Why do you think ning's http client no longer exists?
As for ScribeJava is has optional support of both of them.
You can use ScribeJava with ning or with AHC or without them at all

**Comment by kullfar** [comment]
Are there still any question open?

**Comment by worrel** [comment]
I think the README needs to be updated: `You can use ning async http client 1.9.x or asynchttpclient 2.x out-of-box, just add maven modules scribejava-httpclient-ning or scribejava-httpclient-ahc to your pom`

Those artifacts don't exist on Maven central.  

Also, ServiceBuilder in 2.8.1 has direct dependencies on config objects from both provided libraries, so you need to add both, though I see this is fixed in MASTER.

**Comment by kullfar** [comment]
Oh... README was updated before release... will fix it now.

as for ServiceBuilder in 2.8.1, it has indirect dependency on them. Class loader will not load this classes until you invoke asyncNingHttpClientConfig or asyncAHCHttpClientConfig method.
anyway, you are right, it has completely changed in the MASTER branch

**Comment by kullfar** [comment]
3.0.0  is the maven central now
