### ISSUE TITLE
LinkedIn authorised calls

### ISSUE THREAD

**Issue by AndreaFalcon** [scribejava/scribejava#773]
Hello,
According to this apidoc: https://developer.linkedin.com/docs/oauth2#permissions
the way I make authorised called to LinkedIn API v2 is done appending the Header:

`Authorization: Bearer <access token>`

But I can see that the current implementation append a query parameter called `oauth2_access_token` to the endpoint called.
- Here: https://github.com/scribejava/scribejava/blob/master/scribejava-apis/src/main/java/com/github/scribejava/apis/LinkedInApi20.java#L39
- And here: https://github.com/scribejava/scribejava/blob/master/scribejava-apis/src/main/java/com/github/scribejava/apis/service/LinkedIn20ServiceImpl.java#L17

If I call any endpoint with this way I get 401 Forbidden response code.

**Comment by kullfar** [comment]
Thanks, fixed
https://github.com/scribejava/scribejava/commit/30824b340cc68c6b5670450e3c295a3a108a76ee
in the master

**Comment by FelipeSabedot** [comment]
Hello @AndreaFalcon @kullfar  
I've made the changes on my project with scribejava library updated and I keep receiving the same response as always: 
{
 "errorCode": 0,
 "message": "Invalid access token.",
 "requestId": "PK3SG0IT82",
 "status": 401,
 "timestamp": 1497034919749
}

Everything seems to be ok with my access token since I use the same token on Linkedin-j Api to make a Profile post and it is done successfully.

Do you have any update on that? 
Obs: After updated scribejava library ServiceBuilder() is now deprecated, do you have an alternative for it?

My code:
OAuth20Service service = new ServiceBuilder()
		        .apiKey(InsertByLinkedInAction.CLIENT_ID)
		        .apiSecret(InsertByLinkedInAction.CLIENT_SECRET)
		        .scope("r_basicprofile r_emailaddress rw_company_admin w_share")
		        .build(LinkedInApi20.instance());
		
		OAuth2AccessToken accessToken = new OAuth2AccessToken(profile.getToken());

		JSONObject obj1 = new JSONObject();
		obj1.put("code", "anyone");
		JSONObject obj2 = new JSONObject();
		obj2.put("title", "Test Share with Content");
		obj2.put("description", "content description");
		JSONObject obj = new JSONObject();
		obj.put("visibility", obj1);
		obj.put("comment", "Check out developer.linkedin.com! http://linkd.in/1FC2PyG");
		obj.put("content", obj2);
		
		OAuthRequest request = new OAuthRequest(Verb.POST, "https://api.linkedin.com/v1/companies/"+ profile.getIdProfile()+"/shares");
		//OAuthRequest request = new OAuthRequest(Verb.POST, "https://api.linkedin.com/v1/people/~/shares");
		request.setPayload(obj.toString());
		request.addHeader("Content-Type", "application/json");
		request.addHeader("x-li-format", "json");
		service.signRequest(accessToken, request);
		
		Response response = service.execute(request);

Any comment would be appreciated, and I thank you guys in advance.

**Comment by kullfar** [comment]
> Obs: After updated scribejava library ServiceBuilder() is now deprecated, do you have an alternative for it?

read javadoc on this constructor for the answer

**Comment by kullfar** [comment]
As for the main question - can you see raw http request from Linkedin-j Api and compare it with ScribeJava http request?
