### ISSUE TITLE
azure ad examples - tenant specific examples

### ISSUE THREAD

**Issue by sachinkshetty** [scribejava/scribejava#903]
current azure ad examples are for multi tenant applications only. 
can you please build an example for tenant specific application

**Comment by kullfar** [comment]
Are you sure? As I know there is no such division as "tenant specific application" and "multi tenant application". But I can be wrong. Anyway this issue is out-of-scope for ScribeJava. But you can make such example and create the Pull Request (or pay someone for this job)

**Comment by kullfar** [comment]
You can use
MicrosoftAzureActiveDirectory20Api.instance() for default tenant and
MicrosoftAzureActiveDirectory20Api.custom("customTenant") for a custom.
That's all I know about azure

**Comment by alibenmessaoud** [comment]
> You can use
> MicrosoftAzureActiveDirectory20Api.instance() for default tenant and
> MicrosoftAzureActiveDirectory20Api.custom("customTenant") for a custom.
> That's all I know about azure

The API returns an URL with /common instead of /{tenant-id}
In the code I set the `tenant-id` as follows : 

```
final OAuth20Service service = new ServiceBuilder(clientId)
                .apiSecret(clientSecret)
                .defaultScope("openid User.Read")
                .callback("http://localhost:8201/auth/")
                .build(MicrosoftAzureActiveDirectory20Api.custom("ee736e01-987f-79812f19df56").instance());
```
The given URL is https://login.microsoftonline.com/common/oauth2/v2.0/authorize?response_type=code&client_id=3c65555-49d6-555-d4935&redirect_uri=http%3A%2F%2Flocalhost%3A8201%2Fauth%2F&scope=openid%20User.Read 

I added it manually and it worked.
