### ISSUE TITLE
Unable to route OAuth requests through proxy

### ISSUE THREAD

**Issue by atraista-ellation** [scribejava/scribejava#944]
**Versions:**
com.github.scribejava:scribejava-core:2.5.3
com.github.scribejava:scribejava-apis:2.5.3
io.rest-assured:rest-assured:4.1.1

**Description:**
When I run rest-assured automated tests whith OAuth authentication through intercepting proxy I get an error:

`java.lang.AssertionError: java.lang.IllegalArgumentException: No enum constant com.github.scribejava.core.model.Verb.CONNECT`

Tried different proxies like Charles, BrowserMob, Burpsuite.
Requests w/o OAuth pass through proxy w/o any issues.

**Similar issues:**
[https://github.com/rest-assured/rest-assured/issues/882](https://github.com/rest-assured/rest-assured/issues/882)
[https://github.com/aws/aws-sdk-java/issues/1566#issuecomment-386865044](https://github.com/aws/aws-sdk-java/issues/1566#issuecomment-386865044)

Am I doing something wrong?

**Comment by echorebel** [comment]
probably - we also use charles but w/o issues

**Comment by kullfar** [comment]
@atraista-ellation Hi, as I see the bug was fixed on the rest-assured side. It seems like a right place for the fix.
HTTP verb CONNECT is for starting ssl-tunnels with HTTPS web site. It's lower level, than ScribeJava operates on. I do not think ScribeJava can and should do anything on this level of HTTP protocol. It doesn't use CONNECT method for any OAuth requests.
And the fix in the rest-assured project is correct - to skip such request and do not give it to the ScribeJava processing.
