### ISSUE TITLE
OAuth1: square brackets in query param

### ISSUE THREAD

**Issue by bpietraszuk** [scribejava/scribejava#951]
Hi,

I try to add query params (DBAL Doctrine) to my request: where[0][expr]=gte. However, I receive 401 Unathorized from service I use.

Version: 6.9.0
Authorization method: OAuth1

**Comment by bpietraszuk** [comment]
Any ideas?

**Comment by kullfar** [comment]
Hi, I need more info.
Was the error while making API request or while authorising (acquiring access token)?
You can try to debug what was really send to the server. May be square brackets wasn't escaped in right way.

**Comment by bpietraszuk** [comment]
Hi,

the error occurs during authorising. The request looks like: authToken=someValue&otherParam=someValue?query= where[0][expr]=gte

I tried to escape square brackets but with no result. I suppose there is some problem with & sign.

**Comment by kullfar** [comment]
Hi, I asked "while making API request" **OR** "while authorising (acquiring access token)".
It can't be the same request.
You wrote "during authorising", but then in example I saw "authToken=someValue".

So, please give me more accurate data.

I have tried to use square brackets in different requests in different APIs, all worked good.

It will be great, if you can provide the code example. Or even better Example to run with test user credentials and test app credentials for your API, you have problem with.

**Comment by bpietraszuk** [comment]
I make API request.
Encoded: URL:
GET /api/contacts?where%5B0%5D%5Bval%5D=2020-11-18&search=ids%3A3353&where%5B0%5D%5Bexpr%5D=gte&where%5B1%5D%5Bexpr%5D=lte&where%5B1%5D%5Bcol%5D=dateModified&where%5B0%5D%5Bcol%5D=dateModified&where%5B1%5D%5Bval%5D=2020-11-19
Decoded URL:
GET /api/contacts?where[0][val]=2020-11-18&search=ids:3353&where[0][expr]=gte&where[1][expr]=lte&where[1][col]=dateModified&where[0][col]=dateModified&where[1][val]=2020-11-19

I do not extend com.comarch.aes.ca.crm.scribejava.StringExtractor.
Sample API call code:
```
String url = instanceUrl + request.getEndpoint();
OAuthRequest oauthRequest = prepareRequest(request, url);
service.signRequest(accessToken, oauthRequest);
Response response = oAuthService.execute(oauthRequest);
```

**Comment by kullfar** [comment]
Hi.
First of all, I don't know what is "com.comarch.aes.ca.crm.scribejava.StringExtractor" ;-)
And the method prepareRequest(request, url) from your code snippet is unknown for me.

Next, I found similar issue https://github.com/scribejava/scribejava/issues/947
"Encoding the URL parameters fixes this error." was the solution for it. But it was about semicolon char only.
Maybe you need to escape only some chars in your query. I see semicolon for example in your query. Maybe you should leave square brackets as is and encode only semicolon?

Anyway it looks like the problem is API vendor specific. Can you successfully execute this request somehow else? not with ScribeJava, but maybe curl or any other framework. So we can compare requests send by it and by ScribeJava.

Unfortunately I have no ability to reproduce your problem. I need full java class like https://github.com/scribejava/scribejava/blob/master/scribejava-apis/src/test/java/com/github/scribejava/apis/examples/Google20Example.java
with test app credential and test user credentials provided to me to reproduce the problem and to try to fix it.

If you will find the solution yourself, provide any enhances to the ScribeJava, pls!
