### ISSUE TITLE
Keycloak API Revoke token Exception "Not Implemented Yet"

### ISSUE THREAD

**Issue by danny2394** [scribejava/scribejava#956]
Hi,

I was trying to revoke the token in Keycloak using this library, however, I get the exception that it hasn't been implemented yet.

Keycloak does have a revoke endpoint
http://auth-server/auth/realms/{realm-name}/protocol/openid-connect/logout
which is a POST request and requires the client_id, client_secret and refresh_token in the body of the request

**Comment by maxemann96** [comment]
I think this is because the keycloak implementation is proprietary and not compliant to [rfc 7009](https://tools.ietf.org/html/rfc7009)

More Information can be found in [Pull request](https://github.com/keycloak/keycloak/pull/6704) and [Jira Ticket](https://issues.redhat.com/browse/KEYCLOAK-5325).

The following workaround should work (create Subclass `KeycloakService extends OAuth20Service`).
```
@Override
OAuthRequest createRevokeTokenRequest(String tokenToRevoke, TokenTypeHint tokenTypeHint) {
    OAuthRequest request = super.createRevokeTokenRequest(tokenToRevoke, tokenTypeHint);
    addParameter(OAuthConstants.REFRESH_TOKEN, tokenToRevoke);
    return request;
}

@Override
public Future<Void> revokeToken(String tokenToRevoke, OAuthAsyncRequestCallback<Void> callback,
            TokenTypeHint tokenTypeHint) {
    final OAuthRequest request = createRevokeTokenRequest(tokenToRevoke, tokenTypeHint);

    return execute(request, callback, new OAuthRequest.ResponseConverter<Void>() {
        @Override
        public Void convert(Response response) throws IOException {
            checkForErrorRevokeToken(response);
            return null;
        }
    });
}

private void checkForErrorRevokeToken(Response response) throws IOException {
    if (response.getCode() != 204) {
        OAuth2AccessTokenJsonExtractor.instance().generateError(response.getBody());
    }
}
```

**Comment by kullfar** [comment]
@danny2394, the reason for the exception is simple. It's just not implemented in ScribeJava yet.
```
    @Override
    public String getRevokeTokenEndpoint() {
        throw new RuntimeException("Not implemented yet");
    }
```
(c) https://github.com/scribejava/scribejava/blob/master/scribejava-apis/src/main/java/com/github/scribejava/apis/KeycloakApi.java#L61


@maxemann96 Thanks for the code snippet!

If someone could provide me with application's credentials and test user's credentials to add and run the example, I will add this feature to the ScribeJava. Or better you can provide full Pull Request (with these credentials emailed to me so I can test code changes), I can merge them to the master.

Thx!

**Comment by maxemann96** [comment]
Since keycloak does now provide a rfc 7009 compliant endpoint (see this [Issue](https://github.com/keycloak/keycloak/pull/6704)), the above snippet is now outdated and should **NOT** be used anymore. (The endpoint in the original issue description is intended to be used in conjunction with openid connect 2.0, not with plain oauth). My snippet was just a workaround. 
I think returning the revoke endpoints url should do the magic now, but currently I cannot test it.
